Fix Quiche repo. "dead repo" X_X

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,7 +32,8 @@ jobs:
       - name: Clone QUIC module ⚡
         run: |
           echo "🐚 Cloning Cloudflare quiche..."
-          git clone --recursive -b main https://github.com/cloudflare/quiche.git ../nginx-quic || { echo "💥🐛 ERROR: Could not clone quiche!"; exit 1; }
+          git clone --recursive -b master https://github.com/cloudflare/quiche.git ../nginx-quic \
+            || { echo "💥🐛 ERROR: Could not clone quiche!"; exit 1; }
           echo "✅ QUIC module cloned successfully! 🌈"
 
       - name: Configure & Build NGINX 🔨
